# config/_default/menus.toml

[[main]]
  name = "Projects"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Resume"
  url = "https://raw.githubusercontent.com/ModifiedBear/Resume/master/cv.pdf"
  weight = 40

[[main]]
  name = "GitHub"
  url = "https://github.com/modifiedbear"
  weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
